name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push PHP
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/php-fpm/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shopping-list:latest
      -
        name: Build and push Nginx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shopping-list-nginx:latest

      - name: Restart Docker compose with fresh images
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd /var/www/shopping-list
            git pull
            docker compose --file ./.docker/docker-compose.yml pull
            docker compose --file ./.docker/docker-compose.yml down
            docker volume rm shopping-list_shopping_list_app || true
            docker compose --file ./.docker/docker-compose.yml --env-file ./.docker/.env.prod up -d
            docker exec shopping_list_php bin/console cache:clear --env=prod
            docker exec shopping_list_php bin/console cache:warmup --env=prod
            docker exec shopping_list_php bin/console doctrine:migrations:migrate --no-interaction
